#version: '3.4'
#
#services:
#  web:
#    image: interview_management_system
#    command: gunicorn interview_management_system.wsgi:application --bind 0.0.0.0:8000
#    build: .
#    volumes:
#      - /tmp/interview_management_system/static_root:/app/static
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    links:
#      - postgres
#
#  postgres:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: postgres-user
#      POSTGRES_DB: interview_management_system_db
#    env_file:
#      - .env


services:
  user-service:
    build: ./user_service
    env_file:
      - ./user_service/.env
    depends_on:
      - user-db
    ports:
      - "8001:8000"
  user-db:
    image: postgres:14
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

