# Generated by Django 4.2.6 on 2023-10-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
