# Generated by Django 4.2.6 on 2023-10-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('SALES', 'Sales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('SALES', 'Sales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
