# Generated by Django 4.2.6 on 2023-10-15 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import interview_management_system.interview_management.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('resume_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[interview_management_system.interview_management.custom_validators.future_date_validator])),
                ('time', models.TimeField(validators=[interview_management_system.interview_management.custom_validators.future_time_validator])),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_management.candidate')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_management.job')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_management.candidate')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_management.interview')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_management.job'),
        ),
    ]
