# Generated by Django 4.2.6 on 2023-10-14 20:40

from django.db import migrations, models
import interview_management_system.interview_management.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(validators=[interview_management_system.interview_management.custom_validators.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time',
            field=models.TimeField(validators=[interview_management_system.interview_management.custom_validators.future_time_validator]),
        ),
    ]
