# Generated by Django 4.2.6 on 2023-10-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
