# Generated by Django 4.2.6 on 2023-10-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0002_alter_candidate_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=20),
        ),
    ]
