# Generated by Django 4.2.6 on 2023-10-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0002_interviewfeedbackreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewFeedbackReminder',
        ),
    ]
