# Generated by Django 4.2.6 on 2023-10-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0003_alter_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='date_time',
            field=models.DateField(),
        ),
    ]
