# Generated by Django 4.2.6 on 2023-10-15 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0003_job_candidate_job_alter_interview_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
