# Generated by Django 4.2.6 on 2023-10-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_management', '0005_alter_job_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
